# ~/.config/starship.toml

palette = "catppuccin_macchiato"

format = "$env_var$all"

[fill]
symbol = ' '

[battery]
full_symbol = "󰁹"
empty_symbol = "󰁺"
charging_symbol = "󱟠"
discharging_symbol = "󱟞"
disabled = true

[[battery.display]]
threshold = 100

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 15
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = " [$symbol$branch]($style) "

[git_status]
conflicted = "󰞇 "
ahead = "\\(${count}\\) "
behind = "\\(${count}\\) "
diverged = "󰦻 \\(${ahead_count}/${behind_count}\\) "
untracked = "\\(${count}\\) "
stashed = "󰏗 "
modified = "\\(${count}\\) "
staged = "󱑛\\(${count}\\) "
renamed = "󰈑\\(${count}\\) "
deleted = "✘\\(${count}\\) "
format = "([$all_status$ahead_behind]($style))"

[git_commit]
commit_hash_length = 8

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
disabled = true

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 0
symbol = ""
disabled = true

[time]
time_format = "%T"
format = "󱑔 $time($style) "
disabled = false

[username]
show_always = false

[env_var.PROXY_SNAME]
style="bold surface0"
format="([\\[$env_value\\] ]($style))"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
